# Generated by Django 5.1.2 on 2024-11-21 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=50)),
                ('option', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Land/Plot', 'Land/Plot')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locality', to='owners.property')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_images', models.JSONField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='owners.property')),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('balcony', models.BooleanField(default=False)),
                ('water_supply', models.CharField(blank=True, max_length=20, null=True)),
                ('gym', models.BooleanField(default=False)),
                ('non_veg', models.BooleanField(default=False)),
                ('gated_security', models.BooleanField(default=False)),
                ('show_property_by', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_number', models.CharField(blank=True, max_length=15, null=True)),
                ('similar_units_available', models.BooleanField(default=False)),
                ('directions_tip', models.TextField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='owners.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('apartment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bhk_type', models.CharField(blank=True, max_length=10, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('total_floor', models.IntegerField(blank=True, null=True)),
                ('property_age', models.CharField(blank=True, max_length=20, null=True)),
                ('facing', models.CharField(blank=True, max_length=20, null=True)),
                ('built_up_area', models.FloatField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='owners.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=20)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='owners.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='RentalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_type', models.CharField(choices=[('Rent', 'Only Rent'), ('Lease', 'Only Lease')], max_length=10)),
                ('expected_rent', models.FloatField(blank=True, null=True)),
                ('expected_lease_amount', models.FloatField(blank=True, null=True)),
                ('expected_deposit', models.FloatField(blank=True, null=True)),
                ('monthly_maintenance', models.CharField(blank=True, max_length=20, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('preferred_tenants', models.CharField(blank=True, max_length=50, null=True)),
                ('furnishing', models.CharField(blank=True, max_length=20, null=True)),
                ('parking', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='owners.property')),
            ],
        ),
    ]
